# Generated by Django 2.1.1 on 2019-11-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20191124_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='Main',
        ),
    ]
