# Generated by Django 2.1.1 on 2019-11-29 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20191129_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
